### ISSUE TITLE
De la línea 263 a la 273, las puedes borrar. 

### ISSUE THREAD

**Issue by frodriSanDocente** [Meeryjeins/PHP-practic-SKILLS_UP#5]
https://github.com/Meeryjeins/PHP-practic-SKILLS_UP/blob/18b3c7933e0f02940911b60debe521d327705614/modules/include/new_reg.php#L263

Ese código es de comprobaciones y lo puedes borrar, se te habrá quedado ahí de la parte en que empezamos a verificar las validaciones.

**Comment by Meeryjeins** [comment]
borradas las líneas de la 263 a 273
