### ISSUE TITLE
¿Bintec? ¿Esa función que pasó?

### ISSUE THREAD

**Issue by frodriSanDocente** [Meeryjeins/PHP-practic-SKILLS_UP#6]
https://github.com/Meeryjeins/PHP-practic-SKILLS_UP/blob/18b3c7933e0f02940911b60debe521d327705614/modules/include/new_reg.php#L181

Revisa las funciones de ahí para abajo, que de repente no te gustó como se llamaba. 😝

**Comment by Meeryjeins** [comment]
corregidos los nombres de las variables
